query GetItems($libraryId: ID!, $offset: Int, $limit: Int) {
  items(libraryId: $libraryId, offset: $offset, limit: $limit) {
    items {
      __typename
      id
      title
      thumb
      art
      ... on Movie {
        releaseDate
      }
    }
    total
  }

  library(id: $libraryId) {
    id
    name
  }
}
