query GetLatestHubs($limit: Int) {
  latest(limit: $limit) {
    library {
      id
      name
      type
    }
    items {
      id
      title
      thumb
      ... on Movie {
        releaseDate
      }
    }
  }
}
